/**
 * backend
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface NewFlight { 
    departureIcao: string;
    /**
     * Must be formatted like `2015-07-01 08:59:60 +0000`
     */
    departureTime: Date;
    arrivalIcao: string;
    /**
     * Must be formatted like `2015-07-01 08:59:60 +0000`
     */
    arrivalTime: Date;
}