/**
 * backend
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * This schema provides redirect url's for all configured OAuth providers. If a provider is not configured, a null value is returned
 */
export interface OAuthProviders { 
    /**
     * Redirect url for GitHub OAuth
     */
    github?: string;
}