version: '3.1'
services:
  web:
    image: ghcr.io/projectexchange/skyrocket/frontend:v1.0.0
    restart: always
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:Z"
    networks:
      - web

  backend:
    image: ghcr.io/projectexchange/skyrocket/backend:v1.0.0
    restart: always
    depends_on:
      - "db"
    environment:
      REDIS_URL: ${REDIS_URL}
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_DATABASES: ${ROCKET_DATABASES}
      ROCKET_SECRET_KEY: ${ROCKET_SECRET_KEY}
      OAUTH_GITHUB_CLIENT_ID: ${OAUTH_GITHUB_CLIENT_ID}
      OAUTH_GITHUB_CLIENT_SECRET: ${OAUTH_GITHUB_CLIENT_SECRET}
    volumes:
      - "./certs/mariadb/client/:/home/skyrocket/mysql/:Z"
      - "./certs/ca-cert.pem:/home/skyrocket/mysql/ca-cert.pem:z"
      - "./config/mysql/client.cnf:/home/skyrocket/.my.cnf:Z"
    networks:
      - web
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "./data/db/:/var/lib/mysql/:Z"
      - "./config/mysql/my.cnf:/etc/mysql/conf.d/ssl.cnf:Z"
      - "./config/mysql/encryption/:/etc/mysql/encryption/:Z"
      - "./certs/mariadb/server/:/etc/ssl/mysql/:Z"
      - "./certs/ca-cert.pem:/etc/ssl/mysql/ca-cert.pem:z"
    networks:
      - db

  redis:
    command: "redis-server /usr/local/etc/redis/redis.conf"
    image: redis:alpine
    restart: always
    volumes:
      # should contain redis.conf with `requirepass <YOUR_SECRET_PASS>`
      - "./config/redis/:/usr/local/etc/redis/:Z"
      - "./certs/redis/server:/usr/local/etc/redis/tls/:Z"
      - "./certs/ca-cert.pem:/usr/local/etc/redis/tls/ca-cert.pem:z"
    networks:
      - db

networks:
  db:
    name: skyrocket_db_net
  web:
    name: skyrocket_web_net
