version: '3.1'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - "./data/db:/var/lib/mysql:Z"
      - "./config/mysql/my.cnf:/etc/mysql/conf.d/ssl.cnf:Z"
      - "./config/mysql/encryption/:/etc/mysql/encryption/:Z"
#      - "./config/mysql/certs:/etc/ssl/mysql"
  redis:
    image: redis:alpine
    restart: always
