FROM node:16.13-alpine AS build

WORKDIR /tmp

RUN mkdir ./lib/

COPY ./lib/ng-api-client/ ./lib/ng-api-client/
COPY ./frontend/ ./frontend/

RUN cd lib/ng-api-client/ && npm ci && npm run build
RUN cd frontend/ && npm ci && npm run build


FROM nginx:1.21-alpine

COPY --from=build /tmp/frontend/dist/frontend/ /usr/share/nginx/html/

COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf
